In [163]:
import numpy as np
import torch

$x = \begin{pmatrix}1 \\ -1 \\ 0 \end{pmatrix}, \quad
A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$

$ A \cdot x = \begin{pmatrix} -1 \\ -1 \end{pmatrix}. $

In [164]:
x = torch.tensor([1., -1., 0.], dtype=torch.float)
a = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]), dtype=torch.float)

print("Ax = ")
print(a @ x, "\n")

print("A*x =")
print(a * x)

Ax = 
tensor([-1., -1.]) 

A*x =
tensor([[ 1., -2.,  0.],
        [ 4., -5.,  0.]])


Achtung: `torch.tensor()` kopiert Daten.
Falls ihr ein numpy array inplace in einen Tensor konvertieren wollt, benutzt `torch.as_tensor()`.


$ b = \begin{pmatrix} 1 \\ 2 \end{pmatrix} $

$ \begin{pmatrix} 1 & 1 & 1 \\ 2 & 2 & 2 \end{pmatrix} *
\begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}
= \begin{pmatrix} 1 & 2 & 3 \\ 8 & 10 & 12 \end{pmatrix} $

In [165]:
b = torch.tensor([1, 2])
print("b.repeat(3).view(3,2).T = ")
print(b.repeat(3).view(3,2).T, "\n")

print("b * a = ")
print(b.repeat(3).view(3,2).T * a)

b.repeat(3).view(3,2).T = 
tensor([[1, 1, 1],
        [2, 2, 2]]) 

b * a = 
tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


$I_n$ wird durch `toch.eye(n)` erstellt.

$0_{n,k}$ wird durch `torch.zeros(n, k)` erstellt.

In [ ]:
print(torch.eye(5))
print(torch.zeros(3, 5))

$A_{i,j}$ wird durch `a[i][j]` oder `a[i,j]` erreicht.
Achtung: anders als in z. B. R oder Matlab wird hier nullindiziert.

$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix} $. Also ist $A_{1,1} = 5$.

Einzelne Werte können durch `a[i,j].item()` ausgegeben.

In [167]:
print("a[1,1] = ")
print(a[1,1], "\n")

print("a[1,1].item() = ")
print(a[1,1].item(), "\n")

a[1,1] = 
tensor(5.) 

a[1,1].item() = 
5.0 



$A_{i,*}$ wird durch `a[i,:]` oder `a[i]` erreicht.

$A_{*,i}$ wird durch `a[:,i]` erreicht.

In [168]:
print("a = ")
print(a, "\n")

print("a[0,:] = a[0] = ")
print(a[0,:], "\n")

print("a[:,2] = ")
print(a[:,2], "\n")

a[1,2] = 42
print("a = ")
print(a)

a = 
tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

a[0,:] = a[0] = 
tensor([1., 2., 3.]) 

a[:,2] = 
tensor([3., 6.]) 

a = 
tensor([[ 1.,  2.,  3.],
        [ 4.,  5., 42.]])


$\begin{pmatrix} 22 & \cdots & 42 \end{pmatrix}$ erreichen wir durch `torch.linspace()`

In [169]:
print(torch.linspace(start=22, end=42, steps=42-22+1))

tensor([22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
        36., 37., 38., 39., 40., 41., 42.])


Zufällige Tensoren werden mit `torch.randn(n,k)` erstellt.

In [170]:
print(torch.randn(2,3))

tensor([[-1.6741, -1.2723, -0.3262],
        [ 0.0666,  1.2366,  1.6777]])


$x = \begin{pmatrix} 1 \\ -1 \\ 0 \end{pmatrix}$

$e^x$ bekommen wir durch `torch.exp(x)`.

$||x||_2$ bekommen wir durch `torch.norm(x)`.

$ \sum_{i=1}^n x_i $ bekommen wir durch `torch.sum(x)`.

$ \prod_{i=1}^n x_i $ bekommen wir durch `torch.prod(x)`.

In [171]:
print("torch.exp(x) = ")
print(torch.exp(x), "\n")

print("torch.norm(x) = ")
print(torch.norm(x).item(), "\n")

print("torch.sum(x) = ")
print(torch.sum(x).item(), "\n")

print("torch.prod(x) = ")
print(torch.prod(x).item())

torch.exp(x) = 
tensor([2.7183, 0.3679, 1.0000]) 

torch.norm(x) = 
1.4142135381698608 

torch.sum(x) = 
0.0 

torch.prod(x) = 
-0.0
